package com.landg.mfservice.records.vo;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.1 Build 20180227-1206 on: Tue Jul 14 14:36:44 BST 2020

public class LSOA40Record {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 01  SERVICE-ADAPTER-COMMAREA-DATA. </pre> */
	public static final int SERVICE_ADAPTER_COMMAREA_DATA_len = -1; // contains ODO

	/** <pre>
	*-----------------------------------------------------------
	* SERVICE ADAPTER COMMAREA LAYOUT
	*-----------------------------------------------------------
	*------------------------------------------------------
	* PROCESS SERVER DATA
	*-----------------------------------------------------------
	      03 SA-PROC-SERVER-DATA. </pre> */
	public static final int SA_PROC_SERVER_DATA_len = 38; 
	public static final int SA_PROC_SERVER_DATA_offset = factory.getOffset();

	/** <pre>
	         05 SOAZ1-PRC-CORR-GUID                  PIC X(38). </pre> */
	protected static final StringField SOAZ1_PRC_CORR_GUID = factory.getStringField(38);

	/** <pre>
	*-----------------------------------------------------------
	* SERVER CONTROL DATA
	*-----------------------------------------------------------
	      03 SA-SERVER-CONTROL-DATA. </pre> */
	public static final int SA_SERVER_CONTROL_DATA_len = 1067; 
	public static final int SA_SERVER_CONTROL_DATA_offset = factory.getOffset();

	/** <pre>
	         05 SOAZ2-RETURN-CODE                    PIC S9(04) COMP. </pre> */
	protected static final BinaryAsIntField SOAZ2_RETURN_CODE = factory.getBinaryAsIntField(4, true);

	/** <pre>
	            88 SOAZ2-RETURN-OK                   VALUE ZERO. </pre> */
	public static final int SOAZ2_RETURN_OK = 0;

	/** <pre>
	            88 SOAZ2-RETURN-WARNING              VALUE +04. </pre> */
	public static final int SOAZ2_RETURN_WARNING = 4;

	/** <pre>
	            88 SOAZ2-RETURN-ERROR                VALUE +16. </pre> */
	public static final int SOAZ2_RETURN_ERROR = 16;

	/** <pre>
	            88 SOAZ2-RETURN-SERVICE-UNAVAIL      VALUE +24. </pre> */
	public static final int SOAZ2_RETURN_SERVICE_UNAVAIL = 24;

	/** <pre>
	            88 SOAZ2-RETURN-SERVICE-DISABLED     VALUE +36. </pre> */
	public static final int SOAZ2_RETURN_SERVICE_DISABLED = 36;

	/** <pre>
	         05 SOAZ2-PGM-ID                         PIC X(08). </pre> */
	protected static final StringField SOAZ2_PGM_ID = factory.getStringField(8);

	/** <pre>
	         05 SOAZ2-SA-RETRY-DURATION              PIC X(20). </pre> */
	protected static final StringField SOAZ2_SA_RETRY_DURATION = factory.getStringField(20);

	/** <pre>
	         05 SOAZ2-ERROR-TAG-DATA                 PIC X(30). </pre> */
	protected static final StringField SOAZ2_ERROR_TAG_DATA = factory.getStringField(30);

	/** <pre>
	         05 SOAZ2-ERROR-MSG-NUM                  PIC X(05). </pre> */
	protected static final StringField SOAZ2_ERROR_MSG_NUM = factory.getStringField(5);

	/** <pre>
	         05 SOAZ2-ERROR-MSG-LEN                  PIC S9(04) COMP. </pre> */
	protected static final BinaryAsIntField SOAZ2_ERROR_MSG_LEN = factory.getBinaryAsIntField(4, true);

	/** <pre>
	         05 SOAZ2-ERROR-MSG-TXT                  PIC X(1000). </pre> */
	protected static final StringField SOAZ2_ERROR_MSG_TXT = factory.getStringField(1000);

	/** <pre>
	*-----------------------------------------------------------
	* APPLICATION DATA
	*-----------------------------------------------------------
	     03 SA-APPLICATION-DATA. </pre> */
	public static final int SA_APPLICATION_DATA_len = -1; // contains ODO
	public static final int SA_APPLICATION_DATA_offset = factory.getOffset();

	/** <pre>
	       05 SOA40-APPLIC-INPUT-DATA. </pre> */
	public static final int SOA40_APPLIC_INPUT_DATA_len = -1; // contains ODO
	public static final int SOA40_APPLIC_INPUT_DATA_offset = factory.getOffset();

	/** <pre>
	           10 SOA40-POL-NO                    PIC X(10). </pre> */
	protected static final StringField SOA40_POL_NO = factory.getStringField(10);

	/** <pre>
	           10 SOA40-NO-OF-BUS-FUNC-IDS        PIC 9(3). </pre> */
	protected static final ExternalDecimalAsIntField SOA40_NO_OF_BUS_FUNC_IDS = factory.getExternalDecimalAsIntField(3, false, false, false, false);

	/** <pre>
	           10 SOA40-BUS-FUNC-GROUP. </pre> */
	public static final int SOA40_BUS_FUNC_GROUP_len = -1; // contains ODO
	public static final int SOA40_BUS_FUNC_GROUP_offset = factory.getOffset();

	/** <pre>
	                 15 SOA40-BUS-FUNC-ID           PIC X(4)
	                   OCCURS 1 TO 50 TIMES
	                   DEPENDING ON SOA40-NO-OF-BUS-FUNC-IDS. </pre> */
	protected static final StringField SOA40_BUS_FUNC_ID = factory.getStringField(4);
	public static final int SOA40_BUS_FUNC_ID_num = 50;
	static { factory.setOffset(0); } // storage following is variably located

	/** <pre>
	           05 SOA40-APPLIC-OUTPUT-DATA. </pre> */
	public static final int SOA40_APPLIC_OUTPUT_DATA_len = 15; 
	public static final int SOA40_APPLIC_OUTPUT_DATA_offset = factory.getOffset();

	/** <pre>
	             10 SOA40-WIP-CHECK-PASSED          PIC X(01). </pre> */
	protected static final StringField SOA40_WIP_CHECK_PASSED = factory.getStringField(1);

	/** <pre>
	             10 SOA40-WIP-RETRY-DATE            PIC X(10). </pre> */
	protected static final StringField SOA40_WIP_RETRY_DATE = factory.getStringField(10);

	/** <pre>
	             10 SOA40-WIP-BUS-FUNC-ID           PIC X(04). </pre> */
	protected static final StringField SOA40_WIP_BUS_FUNC_ID = factory.getStringField(4);

	protected byte[] _byteBuffer;
	// Instance variables used to cache field values
	protected String soaz1PrcCorrGuid;
	protected Integer soaz2ReturnCode;
	protected String soaz2PgmId;
	protected String soaz2SaRetryDuration;
	protected String soaz2ErrorTagData;
	protected String soaz2ErrorMsgNum;
	protected Integer soaz2ErrorMsgLen;
	protected String soaz2ErrorMsgTxt;
	protected String soa40PolNo;
	protected Integer soa40NoOfBusFuncIds;
	protected String[] soa40BusFuncId = new String[SOA40_BUS_FUNC_ID_num];
	protected String soa40WipCheckPassed;
	protected String soa40WipRetryDate;
	protected String soa40WipBusFuncId;


	public LSOA40Record (byte[] buffer, boolean bufferContainsData) {
		this._byteBuffer = buffer;
		if (bufferContainsData) {
			cacheOdoSizes();
		}
	}

	private void cacheOdoSizes() {
		soa40NoOfBusFuncIds = new Integer(SOA40_NO_OF_BUS_FUNC_IDS.getInt(_byteBuffer));
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getSoaz1PrcCorrGuid() {
		if (soaz1PrcCorrGuid == null) {
			soaz1PrcCorrGuid = SOAZ1_PRC_CORR_GUID.getString(_byteBuffer);
		}
		return soaz1PrcCorrGuid;
	}

	public void setSoaz1PrcCorrGuid(String soaz1PrcCorrGuid) {
		if (SOAZ1_PRC_CORR_GUID.equals(this.soaz1PrcCorrGuid, soaz1PrcCorrGuid)) {
			return;
		}
		SOAZ1_PRC_CORR_GUID.putString(soaz1PrcCorrGuid, _byteBuffer);
		this.soaz1PrcCorrGuid = soaz1PrcCorrGuid;
	}

	public int getSoaz2ReturnCode() {
		if (soaz2ReturnCode == null) {
			soaz2ReturnCode = new Integer(SOAZ2_RETURN_CODE.getInt(_byteBuffer));
		}
		return soaz2ReturnCode.intValue();
	}

	public void setSoaz2ReturnCode(int soaz2ReturnCode) {
		if (SOAZ2_RETURN_CODE.equals(this.soaz2ReturnCode, soaz2ReturnCode)) {
			return;
		}
		SOAZ2_RETURN_CODE.putInt(soaz2ReturnCode, _byteBuffer);
		this.soaz2ReturnCode = new Integer(soaz2ReturnCode);
	}

	public boolean isSoaz2ReturnOk() {
		return getSoaz2ReturnCode() == SOAZ2_RETURN_OK;
	}

	public boolean isSoaz2ReturnWarning() {
		return getSoaz2ReturnCode() == SOAZ2_RETURN_WARNING;
	}

	public boolean isSoaz2ReturnError() {
		return getSoaz2ReturnCode() == SOAZ2_RETURN_ERROR;
	}

	public boolean isSoaz2ReturnServiceUnavail() {
		return getSoaz2ReturnCode() == SOAZ2_RETURN_SERVICE_UNAVAIL;
	}

	public boolean isSoaz2ReturnServiceDisabled() {
		return getSoaz2ReturnCode() == SOAZ2_RETURN_SERVICE_DISABLED;
	}

	public String getSoaz2PgmId() {
		if (soaz2PgmId == null) {
			soaz2PgmId = SOAZ2_PGM_ID.getString(_byteBuffer);
		}
		return soaz2PgmId;
	}

	public void setSoaz2PgmId(String soaz2PgmId) {
		if (SOAZ2_PGM_ID.equals(this.soaz2PgmId, soaz2PgmId)) {
			return;
		}
		SOAZ2_PGM_ID.putString(soaz2PgmId, _byteBuffer);
		this.soaz2PgmId = soaz2PgmId;
	}

	public String getSoaz2SaRetryDuration() {
		if (soaz2SaRetryDuration == null) {
			soaz2SaRetryDuration = SOAZ2_SA_RETRY_DURATION.getString(_byteBuffer);
		}
		return soaz2SaRetryDuration;
	}

	public void setSoaz2SaRetryDuration(String soaz2SaRetryDuration) {
		if (SOAZ2_SA_RETRY_DURATION.equals(this.soaz2SaRetryDuration, soaz2SaRetryDuration)) {
			return;
		}
		SOAZ2_SA_RETRY_DURATION.putString(soaz2SaRetryDuration, _byteBuffer);
		this.soaz2SaRetryDuration = soaz2SaRetryDuration;
	}

	public String getSoaz2ErrorTagData() {
		if (soaz2ErrorTagData == null) {
			soaz2ErrorTagData = SOAZ2_ERROR_TAG_DATA.getString(_byteBuffer);
		}
		return soaz2ErrorTagData;
	}

	public void setSoaz2ErrorTagData(String soaz2ErrorTagData) {
		if (SOAZ2_ERROR_TAG_DATA.equals(this.soaz2ErrorTagData, soaz2ErrorTagData)) {
			return;
		}
		SOAZ2_ERROR_TAG_DATA.putString(soaz2ErrorTagData, _byteBuffer);
		this.soaz2ErrorTagData = soaz2ErrorTagData;
	}

	public String getSoaz2ErrorMsgNum() {
		if (soaz2ErrorMsgNum == null) {
			soaz2ErrorMsgNum = SOAZ2_ERROR_MSG_NUM.getString(_byteBuffer);
		}
		return soaz2ErrorMsgNum;
	}

	public void setSoaz2ErrorMsgNum(String soaz2ErrorMsgNum) {
		if (SOAZ2_ERROR_MSG_NUM.equals(this.soaz2ErrorMsgNum, soaz2ErrorMsgNum)) {
			return;
		}
		SOAZ2_ERROR_MSG_NUM.putString(soaz2ErrorMsgNum, _byteBuffer);
		this.soaz2ErrorMsgNum = soaz2ErrorMsgNum;
	}

	public int getSoaz2ErrorMsgLen() {
		if (soaz2ErrorMsgLen == null) {
			soaz2ErrorMsgLen = new Integer(SOAZ2_ERROR_MSG_LEN.getInt(_byteBuffer));
		}
		return soaz2ErrorMsgLen.intValue();
	}

	public void setSoaz2ErrorMsgLen(int soaz2ErrorMsgLen) {
		if (SOAZ2_ERROR_MSG_LEN.equals(this.soaz2ErrorMsgLen, soaz2ErrorMsgLen)) {
			return;
		}
		SOAZ2_ERROR_MSG_LEN.putInt(soaz2ErrorMsgLen, _byteBuffer);
		this.soaz2ErrorMsgLen = new Integer(soaz2ErrorMsgLen);
	}

	public String getSoaz2ErrorMsgTxt() {
		if (soaz2ErrorMsgTxt == null) {
			soaz2ErrorMsgTxt = SOAZ2_ERROR_MSG_TXT.getString(_byteBuffer);
		}
		return soaz2ErrorMsgTxt;
	}

	public void setSoaz2ErrorMsgTxt(String soaz2ErrorMsgTxt) {
		if (SOAZ2_ERROR_MSG_TXT.equals(this.soaz2ErrorMsgTxt, soaz2ErrorMsgTxt)) {
			return;
		}
		SOAZ2_ERROR_MSG_TXT.putString(soaz2ErrorMsgTxt, _byteBuffer);
		this.soaz2ErrorMsgTxt = soaz2ErrorMsgTxt;
	}

	public String getSoa40PolNo() {
		if (soa40PolNo == null) {
			soa40PolNo = SOA40_POL_NO.getString(_byteBuffer);
		}
		return soa40PolNo;
	}

	public void setSoa40PolNo(String soa40PolNo) {
		if (SOA40_POL_NO.equals(this.soa40PolNo, soa40PolNo)) {
			return;
		}
		SOA40_POL_NO.putString(soa40PolNo, _byteBuffer);
		this.soa40PolNo = soa40PolNo;
	}

	public int getSoa40NoOfBusFuncIds() {
		if (soa40NoOfBusFuncIds == null) {
			throw new IllegalStateException("ODO object not initialized");
		}
		return soa40NoOfBusFuncIds.intValue();
	}

	public void setSoa40NoOfBusFuncIds(int soa40NoOfBusFuncIds) {
		if (SOA40_NO_OF_BUS_FUNC_IDS.equals(this.soa40NoOfBusFuncIds, soa40NoOfBusFuncIds)) {
			return;
		}
		if (this.soa40NoOfBusFuncIds != null) {
			throw new IllegalStateException("ODO object size may not be altered once set");
		}
		SOA40_NO_OF_BUS_FUNC_IDS.putInt(soa40NoOfBusFuncIds, _byteBuffer);
		this.soa40NoOfBusFuncIds = new Integer(soa40NoOfBusFuncIds);
	}

	public String getSoa40BusFuncId(int _arrayIndex) {
		if (soa40BusFuncId[_arrayIndex] == null) {
			int _arrayOffset = _arrayIndex * SOA40_BUS_FUNC_ID.getByteLength();
			soa40BusFuncId[_arrayIndex] = SOA40_BUS_FUNC_ID.getString(_byteBuffer, _arrayOffset);
		}
		return soa40BusFuncId[_arrayIndex];
	}

	public void setSoa40BusFuncId(int _arrayIndex, String soa40BusFuncId) {
		if (SOA40_BUS_FUNC_ID.equals(this.soa40BusFuncId[_arrayIndex], soa40BusFuncId)) {
			return;
		}
		int _arrayOffset = _arrayIndex * SOA40_BUS_FUNC_ID.getByteLength();
		SOA40_BUS_FUNC_ID.putString(soa40BusFuncId, _byteBuffer, _arrayOffset);
		this.soa40BusFuncId[_arrayIndex] = soa40BusFuncId;
	}

	protected int getSoa40BusFuncId_EndOffset() {
		int start = SOA40_BUS_FUNC_ID.getOffset();
		int curLen = getSoa40NoOfBusFuncIds() * SOA40_BUS_FUNC_ID.getByteLength();
		return start + curLen;
	}

	public String getSoa40WipCheckPassed() {
		if (soa40WipCheckPassed == null) {
			int _variableOffset = getSoa40BusFuncId_EndOffset();
			soa40WipCheckPassed = SOA40_WIP_CHECK_PASSED.getString(_byteBuffer, _variableOffset);
		}
		return soa40WipCheckPassed;
	}

	public void setSoa40WipCheckPassed(String soa40WipCheckPassed) {
		if (SOA40_WIP_CHECK_PASSED.equals(this.soa40WipCheckPassed, soa40WipCheckPassed)) {
			return;
		}
		int _variableOffset = getSoa40BusFuncId_EndOffset();
		SOA40_WIP_CHECK_PASSED.putString(soa40WipCheckPassed, _byteBuffer, _variableOffset);
		this.soa40WipCheckPassed = soa40WipCheckPassed;
	}

	public String getSoa40WipRetryDate() {
		if (soa40WipRetryDate == null) {
			int _variableOffset = getSoa40BusFuncId_EndOffset();
			soa40WipRetryDate = SOA40_WIP_RETRY_DATE.getString(_byteBuffer, _variableOffset);
		}
		return soa40WipRetryDate;
	}

	public void setSoa40WipRetryDate(String soa40WipRetryDate) {
		if (SOA40_WIP_RETRY_DATE.equals(this.soa40WipRetryDate, soa40WipRetryDate)) {
			return;
		}
		int _variableOffset = getSoa40BusFuncId_EndOffset();
		SOA40_WIP_RETRY_DATE.putString(soa40WipRetryDate, _byteBuffer, _variableOffset);
		this.soa40WipRetryDate = soa40WipRetryDate;
	}

	public String getSoa40WipBusFuncId() {
		if (soa40WipBusFuncId == null) {
			int _variableOffset = getSoa40BusFuncId_EndOffset();
			soa40WipBusFuncId = SOA40_WIP_BUS_FUNC_ID.getString(_byteBuffer, _variableOffset);
		}
		return soa40WipBusFuncId;
	}

	public void setSoa40WipBusFuncId(String soa40WipBusFuncId) {
		if (SOA40_WIP_BUS_FUNC_ID.equals(this.soa40WipBusFuncId, soa40WipBusFuncId)) {
			return;
		}
		int _variableOffset = getSoa40BusFuncId_EndOffset();
		SOA40_WIP_BUS_FUNC_ID.putString(soa40WipBusFuncId, _byteBuffer, _variableOffset);
		this.soa40WipBusFuncId = soa40WipBusFuncId;
	}

}
